#! /usr/local/bin/ruby
## -*- Mode: ruby -*-

require "kconv" ;
require "tdb2";

include Kconv ;
include Tdb ;

s = open("Noda1997.tdb") ;

def nop
end

nop

db = scanDB(s) ;

p(db.get('Noda1997c')) ;

print(kconv(db.get('Noda1997c').get("Author"),JIS)) ;

print(kconv(db['Noda1997c']["Author"],JIS)) ;

p(db.slot) ;

p(db.entryList());

